version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  bankrest:
    image: bankrest
    build:
      context: ../../Downloads
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: