spring:
  datasource:
    url: jdbc:postgresql://db:5432/bankdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
springdoc:
  swagger-ui:
    url: /openapi.yml