spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankrest
    username: postgres
    password: hpbox4720
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
